apiVersion: batch/v1
kind: Job

metadata:
  name: e1-helloworld
  namespace: nasrl
  labels:
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/component: experiment-1
    app.kubernetes.io/part-of: nasrl
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - name: nasrl
        image: 10.0.0.8:15050/georgetownschool/nasrl/libnasrl:ci.7af0a7a7
        command: ["python"]
        args: ["-m", "nasrl.exec.hello"]
      restartPolicy: Never